[package]
name = "cprs-cli"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "cargo-cprs-cli"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.36", features = ["derive"] }
